/**
 *  Readme template
 */
const sampleReadmeContent = `# portfolio

> My Portfolio Website, generated by [@abhijithvijayan/portfolio](https://github.com/abhijithvijayan/portfolio-cli) CLI

## 🚀 Quick Start

- \`yarn install\` to install dependencies.
- \`yarn run dev\` to start the development server.
- \`yarn run build\` build the files for production.
- \`yarn run export\` to use Next.js static exports.
- \`yarn run serve\` runs \`build\` and \`export\` commands at once.
<br />

##### 🌟 Updating metadata

Copy \`sample.js\` to \`index.js\` in the \`config /\` directory and update \`config / index.js\` with your custom information

##### 🌟 Adding static contents

Copy contents (images, documents, etc...) to \`public /\` directory

##### 🌟 Adding other site-data

Copy \`sample.md\` to \`index.md\` in the \`markdown / SECTION_NAME\` directory and update accordingly. See [how I did](https://github.com/abhijithvijayan/v6/tree/master/markdown) mine

##### 🌟 PWA Support

Add \`icons for PWA\` to \`public / icons /\` and update \`manifest.json\` in \`public /\` directory

## Show your support

Give a ⭐️ if this project helped you!

## 👨‍🔬 Credits

Template by [abhijithvijayan](https://abhijithvijayan.github.io)
`;

/**
 *  Manifest.json template for PWA
 */
const sampleManifestContent = {
  name: 'Developer',
  short_name: 'Developer',
  icons: [
    {
      src: '',
      sizes: '72x72',
      type: 'image/png',
    },
    {
      src: '',
      sizes: '96x96',
      type: 'image/png',
    },
    {
      src: '',
      sizes: '128x128',
      type: 'image/png',
    },
    {
      src: '',
      sizes: '144x144',
      type: 'image/png',
    },
    {
      src: '',
      sizes: '152x152',
      type: 'image/png',
    },
    {
      src: '',
      sizes: '192x192',
      type: 'image/png',
    },
    {
      src: '',
      sizes: '384x384',
      type: 'image/png',
    },
    {
      src: '',
      sizes: '512x512',
      type: 'image/png',
    },
  ],
  theme_color: '#0a192f',
  background_color: '#020c1b',
  start_url: '/',
  display: 'standalone',
  orientation: 'portrait',
};

const sampleTravisConfigContent = `
language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - 12
git:
  depth: 3
script:
  - yarn run release
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: out
  target-branch: gh-pages
  on:
    branch: master
`;

module.exports = {
  sampleReadmeContent,
  sampleManifestContent,
  sampleTravisConfigContent,
};
